### ISSUE TITLE
Api problem 

### ISSUE THREAD

**Issue by mamaslayer** [gutenacht0221/NachtAuth#2]
Hey, in your tutorial it says "If you want to use the NachtAuth Dashboard, make a new OnRender application and upload the "api" folder to there." 

when I upload the api folder alone to a new application it just doesn't work, 
here is the logs from my application https://pastebin.com/GQNvDV2k
do I need to attach more files when beside the api folder on the application?

**Comment by gutenacht0221** [comment]
I think the issue is that you forgot to change the directory which it starts in
