### ISSUE TITLE
Client_ID error

### ISSUE THREAD

**Issue by SillySkull69** [gutenacht0221/NachtAuth#3]
Jan 9 02:27:25 PM      data: {
Jan 9 02:27:25 PM        error: 'invalid_client',
Jan 9 02:27:25 PM        error_description: "The provided request must include a 'client_id' input parameter.",
Jan 9 02:27:25 PM        correlation_id: 'Yes smth some numbers were here'
Jan 9 02:27:25 PM      }
Jan 9 02:27:25 PM    }
Jan 9 02:27:25 PM  }

Thats the error shown my render logs. What do i do to fix?

**Comment by gutenacht0221** [comment]
believe it or not, you can not follow basic instructions!
