### ISSUE TITLE
Nachtauth bot not available

### ISSUE THREAD

**Issue by githubbrrr** [gutenacht0221/NachtAuth#9]
[](url)the webhook doesnt work anymore since the nachtauth bot removed itself (?), at least its not visible anymore. That means that the rat doesnt work anymore ( at least 4 me).

![image](https://user-images.githubusercontent.com/127704546/227270506-65f5a9e7-ed66-45f4-895e-1f8b20ae32d7.png)

**Comment by githubbrrr** [comment]
![image](https://user-images.githubusercontent.com/127704546/227271008-43a02fa9-ec70-4fcf-8de5-645da6aafa32.png)

**Comment by livingfaraway** [comment]
it sends the token through a webhook... if you need help add me on discord AK-47#4511

**Comment by githubbrrr** [comment]
> it sends the token through a webhook... if you need help add me on discord AK-47#4511

nvm im just quite dumb lmao api key wasnt valid anymore
